MyTaskListManager/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using myProjectApp;
using myProjectApp.BLL;


namespace MyTaskListManager.Controllers
{
    public class ProjectController : Controller
    {

        [HttpGet]
        public ActionResult AddProject()
        {
            ViewBag.Title = "AddProject";
            //var model = new List<Project>();
            //ProjectBLL objMock = new ProjectBLL();
            //model = objMock.GetAll();
            return View("AddProject");
        }
        [HttpGet]
        public ActionResult LoadProjectsDataTable()
        {
            var model = new List<Project>();
            ProjectBLL objMock = new ProjectBLL();
            model = objMock.GetAll();
            return View(model);
        }

        [HttpPost]
        public ActionResult AddProject(Project model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    myProjectApp.Project objMock = new myProjectApp.Project();
                    objMock.Project_Name = model.Project_Name;
                    objMock.Project_Description = model.Project_Description;
                    objMock.Project_Created_Time = model.Project_Created_Time;
                    objMock.Project_Start_Date = model.Project_Start_Date;
                    objMock.Project_End_Date = model.Project_End_Date;
                    objMock.User_Count = model.User_Count;

                    ProjectBLL objBLLMock = new ProjectBLL();

                    try
                    {
                        var ret = objBLLMock.CreateProject(objMock);
                    }
                    catch (Exception)
                    {

                        throw;
                    }
                }                
            }
            catch (Exception)
            {
                return View(model);                
            }
            ModelState.Clear();
            //return View("LoadProjectsDataTable");
            return RedirectToAction("LoadProjectsDataTable");
        }

        // GET: Project/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Project/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Project/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Project/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Project/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Project/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Project/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

MyTaskListManager/Views/Project/AddProject.cshtml
@model myProjectApp.Project

@{
    ViewBag.Title = "AddProject";
    
}

@using (Html.BeginForm("AddProject", "Project", FormMethod.Post))
{
    <div class="row">
        <form id="project" style="width: 100%;">
            <div class="col-lg-12 form-horizontal">
                <h1>Project Manager</h1>
                <fieldset>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Project_Name)
                    </div>
                    <div class="form-group">
                        @Html.TextBoxFor(m => m.Project_Name, new { @type = "text", placeholder = "Name", @class = "title width-7" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Project_Description)
                    </div>
                    <div class="form-group">
                        @Html.TextBoxFor(m => m.Project_Description, new { @type = "text", placeholder = "Description", @class = "title width-7" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(m => m.Project_Created_Time)
                    </div>
                    
                    <div class="form-group">
                        @Html.TextBoxFor(m => m.Project_Created_Time, new { @class = "datefield", @id = "Project_Created_Date", @name = "Project_Created_Date", @type = "datetime-local", @Value = DateTime.Now })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Project_Start_Date)
                    </div>
                    <div class="form-group">
                        @Html.TextBoxFor(m => m.Project_Start_Date, new { @class = "datefield", @id = "Project_Start_Date", @name = "Project_Start_Date", @type = "datetime-local", @Value = DateTime.Now })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(m => m.Project_End_Date)
                    </div>
                    <div class="form-group">
                        @Html.TextBoxFor(m => m.Project_End_Date, new { @class = "datefield", @id = "Project_End_Date", @name = "Project_End_Date", @type = "datetime-local", @Value = DateTime.Now })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(m => m.User_Count)
                    </div>
                    <div class="form-group">
                        @Html.TextBoxFor(m => m.User_Count, new { @type = "text", placeholder = "Count", @class = "title width-7" })
                    </div>
                </fieldset>
            </div>
            <div class="col-lg-12">
                <button type="submit" class="btn btn-success" value="AddProject">Add new project</button>
                <button type="reset" class="btn btn-default">Reset</button>
                <button type="button" class="btn btn-danger" onclick="location.href='@Url.Action("Index", "Home")'">Go Back</button>
            </div>
        </form>
    </div>
}


@*@Html.Partial("LoadProjectsDataTable")
@{ Html.RenderPartial("LoadProjectDataTable");}*@


<br />
<br />

MyTaskListManager/Views/Project/LoadProjectsDataTable.cshtml
@*@model List<myProjectApp.Project>*@
@using myProjectApp.BLL
@using myProjectApp
@model List<Project>
@*IEnumerator IEnumerable.GetEnumerator()*@
@{
    ViewBag.Title = "LoadProjectsDataTable";
    //var Model = new List<Project>();
    //ProjectBLL objMock = new ProjectBLL();
    //Model = objMock.GetAll();

}
@using (Html.BeginForm("LoadProjectsDataTable", "Project",FormMethod.Get))
    {
        <div class="row">
            <table class="table table-stripped">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Description</th>
                        <th>Creation Time</th>
                        <th>Start Date</th>
                        <th>End Date</th>
                        <th>User Count</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                {
                        <tr>
                            <td>
                                @item.Project_Name
                            </td>
                            <td>
                                @item.Project_Description
                            </td>
                            <td>
                                @item.Project_Created_Time
                            </td>
                            <td>
                                @item.Project_Start_Date
                            </td>
                            <td>
                                @item.Project_End_Date
                            </td>
                            <td>
                                @item.User_Count
                            </td>
                            <td>
                                <a href="/Edit/@item.Project_Id">Edit</a>
                                <a href="/Delete/@item.Project_Id">Delete</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    }